name: Lua Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install readline
      run: sudo apt-get update && sudo apt-get install libreadline-dev
    - name: Install D compiler
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-2.095.1
    - name: make
      run: make
    - name: test
      run: ./all
